# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/TopLevel/ip/TopLevel_Datapath_wrapper_0_0/TopLevel_Datapath_wrapper_0_0.xci
# IP: The module: 'TopLevel_Datapath_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/Datapath.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath || ORIG_REF_NAME==Datapath} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_PC_0_0/Datapath_PC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_PC_0_0 || ORIG_REF_NAME==Datapath_PC_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Control_0_0/Datapath_Control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Control_0_0 || ORIG_REF_NAME==Datapath_Control_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_PCADD_0_0/Datapath_PCADD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_PCADD_0_0 || ORIG_REF_NAME==Datapath_PCADD_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2d5_0_0/Datapath_Mux2d5_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2d5_0_0 || ORIG_REF_NAME==Datapath_Mux2d5_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_SignExtend_0_0/Datapath_SignExtend_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_SignExtend_0_0 || ORIG_REF_NAME==Datapath_SignExtend_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2_0_0/Datapath_Mux2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2_0_0 || ORIG_REF_NAME==Datapath_Mux2_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_xlconstant_0_0/Datapath_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_xlconstant_0_0 || ORIG_REF_NAME==Datapath_xlconstant_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_ander_0_0/Datapath_ander_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_ander_0_0 || ORIG_REF_NAME==Datapath_ander_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_ShiftLeft2d26_0_0/Datapath_ShiftLeft2d26_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_ShiftLeft2d26_0_0 || ORIG_REF_NAME==Datapath_ShiftLeft2d26_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_ShiftLeft2_0_0/Datapath_ShiftLeft2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_ShiftLeft2_0_0 || ORIG_REF_NAME==Datapath_ShiftLeft2_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_add_0_0/Datapath_add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_add_0_0 || ORIG_REF_NAME==Datapath_add_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_xlconcat_0_0/Datapath_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_xlconcat_0_0 || ORIG_REF_NAME==Datapath_xlconcat_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_xlslice_0_0/Datapath_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_xlslice_0_0 || ORIG_REF_NAME==Datapath_xlslice_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2_1_0/Datapath_Mux2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2_1_0 || ORIG_REF_NAME==Datapath_Mux2_1_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2_2_0/Datapath_Mux2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2_2_0 || ORIG_REF_NAME==Datapath_Mux2_2_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2_3_0/Datapath_Mux2_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2_3_0 || ORIG_REF_NAME==Datapath_Mux2_3_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_regfile_0_0/Datapath_regfile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_regfile_0_0 || ORIG_REF_NAME==Datapath_regfile_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_datamem_0_0/Datapath_datamem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_datamem_0_0 || ORIG_REF_NAME==Datapath_datamem_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_instmem_0_0/Datapath_instmem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_instmem_0_0 || ORIG_REF_NAME==Datapath_instmem_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_ALUControl_0_0/Datapath_ALUControl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_ALUControl_0_0 || ORIG_REF_NAME==Datapath_ALUControl_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_slicer_0_0/Datapath_slicer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_slicer_0_0 || ORIG_REF_NAME==Datapath_slicer_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_alu_0_0/Datapath_alu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_alu_0_0 || ORIG_REF_NAME==Datapath_alu_0_0} -quiet] -quiet

# XDC: f:/projects/vga/hardware/mipsvga/mipsvga.gen/sources_1/bd/Datapath/Datapath_ooc.xdc

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/TopLevel/ip/TopLevel_Datapath_wrapper_0_0/TopLevel_Datapath_wrapper_0_0.xci
# IP: The module: 'TopLevel_Datapath_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/Datapath.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath || ORIG_REF_NAME==Datapath} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_PC_0_0/Datapath_PC_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_PC_0_0 || ORIG_REF_NAME==Datapath_PC_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Control_0_0/Datapath_Control_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Control_0_0 || ORIG_REF_NAME==Datapath_Control_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_PCADD_0_0/Datapath_PCADD_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_PCADD_0_0 || ORIG_REF_NAME==Datapath_PCADD_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2d5_0_0/Datapath_Mux2d5_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2d5_0_0 || ORIG_REF_NAME==Datapath_Mux2d5_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_SignExtend_0_0/Datapath_SignExtend_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_SignExtend_0_0 || ORIG_REF_NAME==Datapath_SignExtend_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2_0_0/Datapath_Mux2_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2_0_0 || ORIG_REF_NAME==Datapath_Mux2_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_xlconstant_0_0/Datapath_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_xlconstant_0_0 || ORIG_REF_NAME==Datapath_xlconstant_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_ander_0_0/Datapath_ander_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_ander_0_0 || ORIG_REF_NAME==Datapath_ander_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_ShiftLeft2d26_0_0/Datapath_ShiftLeft2d26_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_ShiftLeft2d26_0_0 || ORIG_REF_NAME==Datapath_ShiftLeft2d26_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_ShiftLeft2_0_0/Datapath_ShiftLeft2_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_ShiftLeft2_0_0 || ORIG_REF_NAME==Datapath_ShiftLeft2_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_add_0_0/Datapath_add_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_add_0_0 || ORIG_REF_NAME==Datapath_add_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_xlconcat_0_0/Datapath_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_xlconcat_0_0 || ORIG_REF_NAME==Datapath_xlconcat_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_xlslice_0_0/Datapath_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_xlslice_0_0 || ORIG_REF_NAME==Datapath_xlslice_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2_1_0/Datapath_Mux2_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2_1_0 || ORIG_REF_NAME==Datapath_Mux2_1_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2_2_0/Datapath_Mux2_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2_2_0 || ORIG_REF_NAME==Datapath_Mux2_2_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_Mux2_3_0/Datapath_Mux2_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_Mux2_3_0 || ORIG_REF_NAME==Datapath_Mux2_3_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_regfile_0_0/Datapath_regfile_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_regfile_0_0 || ORIG_REF_NAME==Datapath_regfile_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_datamem_0_0/Datapath_datamem_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_datamem_0_0 || ORIG_REF_NAME==Datapath_datamem_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_instmem_0_0/Datapath_instmem_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_instmem_0_0 || ORIG_REF_NAME==Datapath_instmem_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_ALUControl_0_0/Datapath_ALUControl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_ALUControl_0_0 || ORIG_REF_NAME==Datapath_ALUControl_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_slicer_0_0/Datapath_slicer_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_slicer_0_0 || ORIG_REF_NAME==Datapath_slicer_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/Datapath/ip/Datapath_alu_0_0/Datapath_alu_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Datapath_alu_0_0 || ORIG_REF_NAME==Datapath_alu_0_0} -quiet] -quiet

# XDC: f:/projects/vga/hardware/mipsvga/mipsvga.gen/sources_1/bd/Datapath/Datapath_ooc.xdc
