# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/TopLevel/ip/TopLevel_controller_wrapper_0_0/TopLevel_controller_wrapper_0_0.xci
# IP: The module: 'TopLevel_controller_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/controller.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller || ORIG_REF_NAME==controller} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_color_0_0/controller_color_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_color_0_0 || ORIG_REF_NAME==controller_color_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_hcount_0_0/controller_hcount_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_hcount_0_0 || ORIG_REF_NAME==controller_hcount_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_vcount_0_0/controller_vcount_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_vcount_0_0 || ORIG_REF_NAME==controller_vcount_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_comparator_0_0/controller_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_comparator_0_0 || ORIG_REF_NAME==controller_comparator_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_clockdivider_0_0/controller_clockdivider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_clockdivider_0_0 || ORIG_REF_NAME==controller_clockdivider_0_0} -quiet] -quiet

# XDC: f:/projects/vga/hardware/mipsvga/mipsvga.gen/sources_1/bd/controller/controller_ooc.xdc

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/TopLevel/ip/TopLevel_controller_wrapper_0_0/TopLevel_controller_wrapper_0_0.xci
# IP: The module: 'TopLevel_controller_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/controller.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller || ORIG_REF_NAME==controller} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_color_0_0/controller_color_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_color_0_0 || ORIG_REF_NAME==controller_color_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_hcount_0_0/controller_hcount_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_hcount_0_0 || ORIG_REF_NAME==controller_hcount_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_vcount_0_0/controller_vcount_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_vcount_0_0 || ORIG_REF_NAME==controller_vcount_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_comparator_0_0/controller_comparator_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_comparator_0_0 || ORIG_REF_NAME==controller_comparator_0_0} -quiet] -quiet

# IP: F:/projects/vga/hardware/mipsvga/mipsvga.srcs/sources_1/bd/controller/ip/controller_clockdivider_0_0/controller_clockdivider_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==controller_clockdivider_0_0 || ORIG_REF_NAME==controller_clockdivider_0_0} -quiet] -quiet

# XDC: f:/projects/vga/hardware/mipsvga/mipsvga.gen/sources_1/bd/controller/controller_ooc.xdc
