# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/projects/vga/smallvga/mips.xdc

# Block Designs: bd/Controller/Controller.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Controller || ORIG_REF_NAME==Controller} -quiet] -quiet

# IP: bd/Controller/ip/Controller_datamem_0_0/Controller_datamem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Controller_datamem_0_0 || ORIG_REF_NAME==Controller_datamem_0_0} -quiet] -quiet

# IP: bd/Controller/ip/Controller_hcount_0_0/Controller_hcount_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Controller_hcount_0_0 || ORIG_REF_NAME==Controller_hcount_0_0} -quiet] -quiet

# IP: bd/Controller/ip/Controller_comparator_0_0/Controller_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Controller_comparator_0_0 || ORIG_REF_NAME==Controller_comparator_0_0} -quiet] -quiet

# IP: bd/Controller/ip/Controller_color_0_0/Controller_color_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Controller_color_0_0 || ORIG_REF_NAME==Controller_color_0_0} -quiet] -quiet

# IP: bd/Controller/ip/Controller_vcount_0_0/Controller_vcount_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Controller_vcount_0_0 || ORIG_REF_NAME==Controller_vcount_0_0} -quiet] -quiet

# XDC: f:/projects/vga/smallvga/vgaimage/vgaimage.gen/sources_1/bd/Controller/Controller_ooc.xdc
